### PR TITLE
I have simplified the tensorrt model inference codes and it works for me.

### PR DESCRIPTION
**Pull request by lbq779660843**
Flow:
1. export onnx to engine by using.
```bash
trtexec --onnx=depth_anything_vitb14.onnx --saveEngine=depth_anything_vitb14.engine
```
2.modify CMakelists.txt, change **TensorRT** and **OpenCV** pathes.

3.modify main.cpp,change **FileFormat**, **depthEngineFile**, **VideoPath** and **imageFolderPath** these variables.

4.build project by using camke-gui or following commands.

```bash
mkdir build
cd build
cmake ..
make
```

Then you can use the new project.

### CODE REVIEW

**Comment by spacewalk01** [comment]
Thank you for your contribution. I will test it on my machine. If there isn't any issue, then I will merge your pull request.

**Comment by spacewalk01** [comment]
Before that, please resolve conflicts issue.

**Comment by lbq779660843** [comment]
It's more convenient to consider reconstructing this rep if the new merge passes the test on your machine, and I have no access to modify any file.

**Comment by spacewalk01** [comment]
Updating your fork with recent changes will fix the confliction issue!

**Pull request closed without merging**
