### PR TITLE
CLI functionality

### PR DESCRIPTION
**Pull request by xa1on**
Treat depth-anything-tensorrt like a command line interface with multiple different flags and arguments. This also allows for the processing of entire folders of both videos and images.
Refer to readme to find changes.

### CODE REVIEW

**Review by spacewalk01 — CHANGES_REQUESTED** [review]
include win32 and tensorrt10 support

**Comment by xa1on** [comment]
win32 & tensorrt 10 support added

**Comment by spacewalk01** [comment]
Hi, I got the following two errors when running your fork: 

1). main.cpp(99,19): error C2512: 'DepthAnything': no appropriate default constructor available 

2). main.cpp(141,21): error C2039: 'init': is not a member of 'DepthAnything'

**Comment by xa1on** [comment]
Sorry, small oversight. Should be fixed now! @spacewalk01

**Comment by spacewalk01** [comment]
thank you for your contribution!

**Pull request merged**
